apiVersion: apps/v1
kind: Deployment
metadata:
  name: oschat
  labels:
    app: oschat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oschat
  template:
    metadata:
      labels:
        app: oschat
    spec:
      containers:
      - name: oschat
        image: harshau04/oschat:latest
        ports:
        - containerPort: 3000

